global:
  imageRegistry: null

image:
  registry: ghcr.io
  repository: bodgit/nri-plugin-runtime
  tag: v0.0.3@sha256:130c0b1b6fa3952501e0d2ff1aefb55eadb86d8adf94aae3a5269b265e10122e
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name:
  labels: {}

nri:
  plugin:
    index: 90
  runtime:
    patchConfig: false

podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
  seccompProfile:
    type: RuntimeDefault

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 32Mi

tolerations:
  - operator: Exists

podPriorityClassName: system-node-critical

initContainerImage:
  registry: ghcr.io
  repository: containers/nri-plugins/nri-config-manager
  tag: v0.12.2@sha256:c75524531ed8f100f19abf410eb47bc0674eb5e33d25c00b72ca1665a1d30b5c
  pullPolicy: IfNotPresent
