global:
  imageRegistry: null

image:
  registry: ghcr.io
  repository: bodgit/nri-plugin-runtime
  tag: v0.0.1@sha256:091bc47679ebad6bd4c2fd5fd555d587c94de09d44fff70cf8c62b6b077bed00
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name:
  labels: {}

nri:
  plugin:
    index: 90
  runtime:
    patchConfig: false

podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
  seccompProfile:
    type: RuntimeDefault

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 32Mi

tolerations:
  - operator: Exists

podPriorityClassName: system-node-critical

initContainerImage:
  registry: ghcr.io
  repository: containers/nri-plugins/nri-config-manager
  tag: v0.9.4@sha256:911d5f94f3a7a545e5d7c854e2f0a2b7083b268dd3795022c7bf4c9ca0cc30ae
  pullPolicy: IfNotPresent
