global:
  imageRegistry: null

image:
  registry: ghcr.io
  repository: bodgit/nri-plugin-runtime
  tag: v0.0.2@sha256:28cd859856129fac9cbd90dfaf0641061987db91cdf54f68d04ed33b5a035553
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name:
  labels: {}

nri:
  plugin:
    index: 90
  runtime:
    patchConfig: false

podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
  seccompProfile:
    type: RuntimeDefault

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 32Mi

tolerations:
  - operator: Exists

podPriorityClassName: system-node-critical

initContainerImage:
  registry: ghcr.io
  repository: containers/nri-plugins/nri-config-manager
  tag: v0.10.0@sha256:8bc466ae1225a70ba20d46425f9d53ba59d99b9d1d0795f1dd8dcff60ea6c785
  pullPolicy: IfNotPresent
