name: Publish Helm chart to GHCR

on:
  push:
    branches:
      - '!*'
    tags:
      - 'nri-plugin-runtime-*'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  helm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Helm chart
        shell: bash
        run: |
          helm package deploy/helm
          helm push nri-plugin-runtime-${GITHUB_REF_NAME##*-}.tgz oci://ghcr.io/bodgit/chart
